dist: xenial
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'

install:
- python setup.py install
- pip install Pygments collective.checkdocs

script:
- python setup.py test
- python setup.py checkdocs

after_success:
- bash <(curl -s https://codecov.io/bash)
